app:
    defaultoutput: table
    defaultmode: cli
    timeoutseconds: 30
    maxconcurrency: 8
aws:
    profile: default
    authmethod: auto
    regions:
        - us-east-1
    allregions: false
    sts:
        rolearn: ""
        sessionname: ""
        externalid: ""
        mfaserial: ""
        duration: 0
    static:
        accesskeyid: ""
        secretaccesskey: ""
        sessiontoken: ""
services:
    cloudwatch:
        enabled: true
        resources: {}
    dynamodb:
        enabled: true
        resources: {}
    ec2:
        enabled: true
        resources: {}
    ecs:
        enabled: true
        resources: {}
    eks:
        enabled: true
        resources: {}
    elbv2:
        enabled: true
        resources: {}
    emr:
        enabled: true
        resources: {}
    iam:
        enabled: true
        resources: {}
    lambda:
        enabled: true
        resources: {}
    rds:
        enabled: true
        resources: {}
    route53:
        enabled: true
        resources: {}
    s3:
        enabled: true
        resources: {}
    secretsmanager:
        enabled: true
        resources: {}
    sns:
        enabled: true
        resources: {}
    sqs:
        enabled: true
        resources: {}
filters:
    regions: []
    tags: {}
    states: []
output:
    format: table
    includedetails: false
    fields: []
ui:
    theme: princess-parrot
    themes:
        bee-eater:
            heading: '#BDD9D7'
            text: '#BDD9D7'
            background: ""
            border: '#03363D'
            highlight: '#BDD9D7'
            highlighttext: '#03363D'
            muted: '#03363D'
            error: '#FF5555'
            warning: '#FFAA00'
        blue-winged-kookaburra:
            heading: '#4169E1'
            text: '#4169E1'
            background: ""
            border: '#D2691E'
            highlight: '#4169E1'
            highlighttext: '#D2691E'
            muted: '#D2691E'
            error: '#FF5555'
            warning: '#FFAA00'
        cassowary:
            heading: '#191970'
            text: '#DC143C'
            background: ""
            border: '#DC143C'
            highlight: '#191970'
            highlighttext: '#DC143C'
            muted: '#DC143C'
            error: '#FF5555'
            warning: '#FFAA00'
        eastern-rosella:
            heading: '#FCDB32'
            text: '#FCDB32'
            background: ""
            border: '#141D38'
            highlight: '#FCDB32'
            highlighttext: '#141D38'
            muted: '#141D38'
            error: '#FF5555'
            warning: '#FFAA00'
        galah:
            heading: '#FF69B4'
            text: '#FF69B4'
            background: ""
            border: '#808080'
            highlight: '#FF69B4'
            highlighttext: '#808080'
            muted: '#808080'
            error: '#FF5555'
            warning: '#FFAA00'
        oriole:
            heading: '#34E0A1'
            text: '#34E0A1'
            background: ""
            border: '#000000'
            highlight: '#34E0A1'
            highlighttext: '#000000'
            muted: '#888888'
            error: '#FF5555'
            warning: '#FFAA00'
        plains-wanderer:
            heading: '#9FE870'
            text: '#9FE870'
            background: ""
            border: '#163300'
            highlight: '#9FE870'
            highlighttext: '#163300'
            muted: '#163300'
            error: '#FF5555'
            warning: '#FFAA00'
        princess-parrot:
            heading: '#FF69B4'
            text: '#FF69B4'
            background: ""
            border: '#006400'
            highlight: '#FF69B4'
            highlighttext: '#006400'
            muted: '#006400'
            error: '#FF5555'
            warning: '#FFAA00'
        rose-crowned-fruit-dove:
            heading: '#3447AA'
            text: '#FBEAEB'
            background: ""
            border: '#FBEAEB'
            highlight: '#3447AA'
            highlighttext: '#FBEAEB'
            muted: '#FBEAEB'
            error: '#FF5555'
            warning: '#FFAA00'
        spotted-pardalote:
            heading: '#6260FF'
            text: '#E4E4FF'
            background: ""
            border: '#E4E4FF'
            highlight: '#6260FF'
            highlighttext: '#E4E4FF'
            muted: '#E4E4FF'
            error: '#FF5555'
            warning: '#FFAA00'
        superb-fairy-wren:
            heading: '#1E90FF'
            text: '#1E90FF'
            background: ""
            border: '#8B4513'
            highlight: '#1E90FF'
            highlighttext: '#8B4513'
            muted: '#8B4513'
            error: '#FF5555'
            warning: '#FFAA00'
        yellow-robin:
            heading: '#FFD700'
            text: '#FFD700'
            background: ""
            border: '#696969'
            highlight: '#FFD700'
            highlighttext: '#696969'
            muted: '#696969'
            error: '#FF5555'
            warning: '#FFAA00'
