// Package table provides a simple table component for Bubble Tea applications.
// Based on github.com/charmbracelet/bubbles/table (MIT License).
// Modified to apply the Selected style per-cell so the highlight background
// spans the full row width instead of only the first column.
package table

import (
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/x/ansi"
	"github.com/mattn/go-runewidth"

	"github.com/charmbracelet/bubbles/help"
	"github.com/charmbracelet/bubbles/key"
	"github.com/charmbracelet/bubbles/viewport"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap KeyMap
	Help   help.Model

	// MarkRow, when set, wraps each rendered row just before it enters the
	// viewport. Callers use it to register a mouse hit-zone per visible row
	// (e.g. with bubblezone) so rows can be selected by clicking.
	MarkRow func(index int, rendered string) string

	cols   []Column
	rows   []Row
	cursor int
	focus  bool
	styles Styles

	// Horizontal column scrolling. width is the available render width (0 means
	// unconstrained / show every column). frozenCols leading columns are pinned
	// and always shown; colOffset counts how many of the remaining (scrollable)
	// columns are hidden off the left edge.
	width      int
	colOffset  int
	frozenCols int

	// baseWidths holds each column's configured width, captured before any
	// content-based auto-fit. It is the floor a column may shrink to; columns
	// grow past it to fit their widest cell so values are never truncated.
	baseWidths []int

	// colStyles caches the per-column Width/MaxWidth/Inline cell style,
	// rebuilt when column widths change (fitColumns) instead of being
	// re-allocated for every cell on every frame.
	colStyles []lipgloss.Style
	// selCellStyle caches the selected-row cell style derived from styles,
	// rebuilt in SetStyles instead of per render.
	selCellStyle lipgloss.Style

	viewport viewport.Model
	start    int
	end      int
}

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	LineUp       key.Binding
	LineDown     key.Binding
	PageUp       key.Binding
	PageDown     key.Binding
	HalfPageUp   key.Binding
	HalfPageDown key.Binding
	GotoTop      key.Binding
	GotoBottom   key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.LineUp, km.LineDown}
}

// FullHelp implements the KeyMap interface.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.LineUp, km.LineDown, km.GotoTop, km.GotoBottom},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
	}
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() KeyMap {
	const spacebar = " "
	return KeyMap{
		LineUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown", spacebar),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style

	// ScrollTrack and ScrollThumb style the vertical scrollbar drawn down the
	// right edge when there are more rows than fit. Zero values render an
	// uncolored bar, which is still legible; ui.TableStyles themes them.
	ScrollTrack lipgloss.Style
	ScrollThumb lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *Model) SetStyles(s Styles) {
	m.styles = s
	m.refreshSelStyle()
	m.UpdateViewport()
}

// refreshSelStyle rebuilds the cached selected-row cell style: Cell's padding
// with Selected's colors/bold, so the highlight background covers each cell's
// full width (including padding) rather than being broken by per-cell ANSI
// resets when Cell has its own foreground color set.
func (m *Model) refreshSelStyle() {
	m.selCellStyle = m.styles.Cell.
		Foreground(m.styles.Selected.GetForeground()).
		Background(m.styles.Selected.GetBackground()).
		Bold(m.styles.Selected.GetBold())
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(opts ...Option) Model {
	m := Model{
		cursor:   0,
		viewport: viewport.New(0, 20), //nolint:mnd

		frozenCols: 1, // pin the leading column (e.g. the row-number "#") by default

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: DefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.refreshSelStyle()
	m.fitColumns()
	m.UpdateViewport()

	return m
}

// fitColumns grows every visible column (one with a configured width > 0) so it
// is at least as wide as its widest cell and its header. Columns never shrink
// below their configured width (the floor captured in baseWidths), and columns
// configured with width 0 stay hidden. Because cells are sized to fit, the
// per-cell truncation in renderRow never elides content; tables that overflow
// the view scroll horizontally by whole columns instead (see ScrollRight).
func (m *Model) fitColumns() {
	if len(m.baseWidths) != len(m.cols) {
		m.baseWidths = make([]int, len(m.cols))
		for i, c := range m.cols {
			m.baseWidths[i] = c.Width
		}
	}

	for i := range m.cols {
		base := m.baseWidths[i]
		if base <= 0 {
			// Width-0 columns are intentionally hidden from the table.
			m.cols[i].Width = base
			continue
		}
		w := max(base, runewidth.StringWidth(m.cols[i].Title))
		for _, row := range m.rows {
			if i < len(row) {
				if cw := runewidth.StringWidth(row[i]); cw > w {
					w = cw
				}
			}
		}
		m.cols[i].Width = w
	}

	// Widths are final for this column/row set: rebuild the per-column style
	// cache used by renderRow and headersView.
	m.colStyles = make([]lipgloss.Style, len(m.cols))
	for i, c := range m.cols {
		m.colStyles[i] = lipgloss.NewStyle().Width(c.Width).MaxWidth(c.Width).Inline(true)
	}
}

// colStyle returns the cached per-column style, building one on the fly only
// when the cache isn't populated yet (e.g. option callbacks during New).
func (m Model) colStyle(i int) lipgloss.Style {
	if i < len(m.colStyles) {
		return m.colStyles[i]
	}
	return lipgloss.NewStyle().Width(m.cols[i].Width).MaxWidth(m.cols[i].Width).Inline(true)
}

// SortAscArrow and SortDescArrow are the header suffixes marking the active
// sort column and its direction. Each is two display cells wide (a separating
// space plus the arrow) so the two directions are interchangeable without
// changing a header's width.
const (
	SortAscArrow  = " ↑"
	SortDescArrow = " ↓"
)

// ApplySortHeader marks the active sort column's header with a direction arrow
// (SortAscArrow / SortDescArrow) and reserves room for that arrow in every
// sortable column's width. Because the width is reserved whether or not the
// column currently shows the arrow, the arrow appearing — or moving between
// columns — never changes a column's width, so the table does not reflow
// ("flicker"). Inactive sortable headers stay arrow-free for a clean look.
//
// active is the index of the current sort column, or -1 for none. sortable
// reports whether column i participates in sorting, so non-sortable columns
// (e.g. a positional "#") are left untouched. Call it each render with freshly
// built, arrow-free columns.
func ApplySortHeader(cols []Column, active int, asc bool, sortable func(i int) bool) {
	arrow := SortAscArrow
	if !asc {
		arrow = SortDescArrow
	}
	arrowW := runewidth.StringWidth(arrow)
	for i := range cols {
		if cols[i].Width == 0 || !sortable(i) {
			continue // width-0 columns are hidden; non-sortable ones never sort
		}
		if reserved := runewidth.StringWidth(cols[i].Title) + arrowW; cols[i].Width < reserved {
			cols[i].Width = reserved
		}
		if i == active {
			cols[i].Title += arrow
		}
	}
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.viewport.Height = h - lipgloss.Height(m.headersView())
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.viewport.Width = w
	}
}

// WithFrozenColumns sets how many leading columns are pinned (never scrolled
// off) during horizontal column scrolling.
func WithFrozenColumns(n int) Option {
	return func(m *Model) {
		if n < 0 {
			n = 0
		}
		m.frozenCols = n
	}
}

// WithFocused sets the focus state of the table.
func WithFocused(f bool) Option {
	return func(m *Model) {
		m.focus = f
	}
}

// WithStyles sets the table styles.
func WithStyles(s Styles) Option {
	return func(m *Model) {
		m.styles = s
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height)
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height)
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.UpdateViewport()
}

// vScrollGutter is the width reserved on the right for the vertical scrollbar
// (one spacer column plus the bar) when the table has more rows than fit.
const vScrollGutter = 2

// vScrollActive reports whether a vertical scrollbar is shown: the table has a
// constrained width and more rows than the row viewport can display at once.
func (m Model) vScrollActive() bool {
	return m.width > 0 && m.viewport.Height > 0 && len(m.rows) > m.viewport.Height
}

// contentWidth is the width available to columns: the render width minus the
// scrollbar gutter when one is shown, so the bar never pushes the table past
// the width the caller sized it to.
func (m Model) contentWidth() int {
	if m.vScrollActive() {
		return m.width - vScrollGutter
	}
	return m.width
}

// View renders the component.
func (m Model) View() string {
	header := m.headersView()
	rows := m.viewport.View()
	if !m.vScrollActive() {
		return header + "\n" + rows
	}

	// Pair the row area with a vertical scrollbar so a full page no longer hides
	// the fact that there are more rows above/below (issue #155). The bar tracks
	// the topmost visible row within the full row set.
	cw := m.contentWidth()
	top := m.start + m.viewport.YOffset
	bar := RenderVScrollbar(m.viewport.Height, len(m.rows), m.viewport.Height, top,
		m.styles.ScrollTrack, m.styles.ScrollThumb)
	barLines := strings.Split(bar, "\n")

	// Pad each row line to the content width so the bar lands flush at the right
	// edge regardless of how short the widest row is. MaxWidth trims the trailing
	// padding the viewport may add, keeping every line exactly cw + gutter wide.
	pad := lipgloss.NewStyle().Width(cw).MaxWidth(cw)
	rowLines := strings.Split(rows, "\n")
	for i := range rowLines {
		line := pad.Render(rowLines[i])
		if i < len(barLines) {
			line += " " + barLines[i]
		}
		rowLines[i] = line
	}
	return header + "\n" + strings.Join(rowLines, "\n")
}

// RenderVScrollbar renders a one-column vertical scrollbar of the given height:
// a thumb sized to the visible fraction of the content, positioned by the
// scroll offset. When everything fits (total <= visible) it returns a blank
// gutter of spaces so callers can reserve the column unconditionally. track and
// thumb style the respective cells. It lives here (rather than in internal/ui)
// so the table can draw its own scrollbar without importing ui, which imports
// table; ui.VScrollbar delegates to it.
//
// total is the content's line count, visible the number of lines on screen and
// offset the index of the topmost visible line.
func RenderVScrollbar(height, total, visible, offset int, track, thumb lipgloss.Style) string {
	if height < 1 {
		return ""
	}
	blank := strings.TrimRight(strings.Repeat(" \n", height), "\n")
	if total <= visible || visible < 1 {
		return blank
	}

	thumbH := height * visible / total
	if thumbH < 1 {
		thumbH = 1
	}
	if thumbH > height {
		thumbH = height
	}

	maxOffset := total - visible
	travel := height - thumbH
	pos := 0
	if maxOffset > 0 {
		pos = travel * offset / maxOffset
	}
	if pos > travel {
		pos = travel
	}
	if pos < 0 {
		pos = 0
	}

	var b strings.Builder
	for i := 0; i < height; i++ {
		if i > 0 {
			b.WriteByte('\n')
		}
		if i >= pos && i < pos+thumbH {
			b.WriteString(thumb.Render("┃"))
		} else {
			b.WriteString(track.Render("│"))
		}
	}
	return b.String()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *Model) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor >= 0 {
		m.start = clamp(m.cursor-m.viewport.Height, 0, m.cursor)
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor+m.viewport.Height, m.cursor, len(m.rows))
	vis := m.visibleCols() // resolved once per refresh, not once per row
	for i := m.start; i < m.end; i++ {
		row := m.renderRow(i, vis)
		if m.MarkRow != nil {
			row = m.MarkRow(i, row)
		}
		renderedRows = append(renderedRows, row)
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// VisibleRange returns the half-open [start, end) row index range currently
// rendered into the viewport — the only rows that can have a mouse hit-zone.
func (m Model) VisibleRange() (start, end int) {
	return m.start, m.end
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m Model) SelectedRow() Row {
	if m.cursor < 0 || m.cursor >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor]
}

// Rows returns the current rows.
func (m Model) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m Model) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor > len(m.rows)-1 {
		m.cursor = len(m.rows) - 1
	}
	// Recover from an empty row set (cursor -1) once rows arrive, so the
	// first row is selected without requiring a cursor movement first.
	if m.cursor < 0 && len(m.rows) > 0 {
		m.cursor = 0
	}

	m.fitColumns()
	if max := m.maxColOffset(); m.colOffset > max {
		m.colOffset = max
	}
	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.baseWidths = nil // recapture configured widths for the new column set
	m.colOffset = 0    // new column set: start scrolled fully left
	m.fitColumns()
	m.UpdateViewport()
}

// SetWidth sets the render width available to the table. Columns that do not
// fit are scrolled rather than truncated; see ScrollLeft / ScrollRight.
func (m *Model) SetWidth(w int) {
	m.width = w
	m.viewport.Width = w
	if max := m.maxColOffset(); m.colOffset > max {
		m.colOffset = max
	}
	m.UpdateViewport()
}

// ScrollRight reveals the next hidden column on the right, if any.
func (m *Model) ScrollRight() {
	if m.colOffset < m.maxColOffset() {
		m.colOffset++
		m.UpdateViewport()
	}
}

// ScrollLeft reveals the previous hidden column on the left, if any.
func (m *Model) ScrollLeft() {
	if m.colOffset > 0 {
		m.colOffset--
		m.UpdateViewport()
	}
}

// ColScrollInfo reports how many scrollable (non-frozen) columns are currently
// hidden off the left and right edges. Both zero means every column is visible.
func (m Model) ColScrollInfo() (hiddenLeft, hiddenRight int) {
	pos, frozen := m.layoutCols()
	scroll := pos[frozen:]
	if m.contentWidth() <= 0 || len(scroll) == 0 {
		return 0, 0
	}
	hiddenLeft = m.colOffset
	if hiddenLeft > len(scroll) {
		hiddenLeft = len(scroll)
	}
	visScroll := len(m.visibleCols()) - frozen
	hiddenRight = len(scroll) - hiddenLeft - visScroll
	if hiddenRight < 0 {
		hiddenRight = 0
	}
	return hiddenLeft, hiddenRight
}

// layoutCols returns the indexes of columns with a positive width (the ones
// that actually render) and the effective number of frozen leading columns.
func (m Model) layoutCols() (pos []int, frozen int) {
	for i, c := range m.cols {
		if c.Width > 0 {
			pos = append(pos, i)
		}
	}
	frozen = m.frozenCols
	if frozen > len(pos) {
		frozen = len(pos)
	}
	return pos, frozen
}

// colSpan is the on-screen width a column occupies, including cell padding.
func (m Model) colSpan(i int) int {
	return m.cols[i].Width + m.styles.Cell.GetHorizontalPadding()
}

// visibleCols returns the column indexes to render given the current width and
// scroll offset: the frozen columns followed by as many scrollable columns
// (starting at colOffset) as fit.
func (m Model) visibleCols() []int {
	pos, frozen := m.layoutCols()
	cw := m.contentWidth()
	if cw <= 0 {
		return pos
	}
	res := append([]int{}, pos[:frozen]...)
	used := 0
	for _, i := range res {
		used += m.colSpan(i)
	}
	scroll := pos[frozen:]
	off := m.colOffset
	if off > len(scroll) {
		off = len(scroll)
	}
	for k := off; k < len(scroll); k++ {
		span := m.colSpan(scroll[k])
		if used+span > cw && len(res) > frozen {
			break
		}
		res = append(res, scroll[k])
		used += span
	}
	return res
}

// maxColOffset is the largest colOffset that still fills the view from the
// right edge, so scrolling never reveals empty space past the last column.
func (m Model) maxColOffset() int {
	pos, frozen := m.layoutCols()
	scroll := pos[frozen:]
	cw := m.contentWidth()
	if cw <= 0 || len(scroll) == 0 {
		return 0
	}
	avail := cw
	for _, i := range pos[:frozen] {
		avail -= m.colSpan(i)
	}
	used, fit := 0, 0
	for k := len(scroll) - 1; k >= 0; k-- {
		span := m.colSpan(scroll[k])
		if used+span > avail && fit > 0 {
			break
		}
		used += span
		fit++
	}
	if mo := len(scroll) - fit; mo > 0 {
		return mo
	}
	return 0
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.viewport.Height = h - lipgloss.Height(m.headersView())
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m Model) Height() int {
	return m.viewport.Height
}

// Width returns the viewport width of the table.
func (m Model) Width() int {
	return m.viewport.Width
}

// Cursor returns the index of the selected row.
func (m Model) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *Model) SetCursor(n int) {
	m.cursor = clamp(n, 0, len(m.rows)-1)
	m.UpdateViewport()
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, len(m.rows)-1)
	switch {
	case m.start == 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset, 0, m.cursor))
	case m.start < m.viewport.Height:
		m.viewport.YOffset = (clamp(clamp(m.viewport.YOffset+n, 0, m.cursor), 0, m.viewport.Height))
	case m.viewport.YOffset >= 1:
		m.viewport.YOffset = clamp(m.viewport.YOffset+n, 1, m.viewport.Height)
	}
	m.UpdateViewport()
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, len(m.rows)-1)
	m.UpdateViewport()

	switch {
	case m.end == len(m.rows) && m.viewport.YOffset > 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset-n, 1, m.viewport.Height))
	case m.cursor > (m.end-m.start)/2 && m.viewport.YOffset > 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset-n, 1, m.cursor))
	case m.viewport.YOffset > 1:
	case m.cursor > m.viewport.YOffset+m.viewport.Height-1:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset+1, 0, 1))
	}
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{}
	for _, line := range strings.Split(value, "\n") {
		r := Row{}
		for _, field := range strings.Split(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m Model) headersView() string {
	vis := m.visibleCols()
	s := make([]string, 0, len(vis))
	for _, i := range vis {
		col := m.cols[i]
		renderedCell := m.colStyle(i).Render(runewidth.Truncate(col.Title, col.Width, "…"))
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	return m.clipToWidth(lipgloss.JoinHorizontal(lipgloss.Top, s...))
}

// clipToWidth hard-truncates every line of s to the table's render width so a
// row can never be wider than the table — even when a single auto-fit column is
// wider than the whole view (the "always show at least one column" rule can
// otherwise force an overflow). Without this, the surrounding panel wraps the
// excess onto a new line and corrupts the layout. A width of 0 means
// unconstrained, so nothing is clipped.
func (m Model) clipToWidth(s string) string {
	w := m.contentWidth()
	if w <= 0 {
		return s
	}
	if !strings.Contains(s, "\n") {
		return ansi.Truncate(s, w, "")
	}
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		lines[i] = ansi.Truncate(ln, w, "")
	}
	return strings.Join(lines, "\n")
}

func (m *Model) renderRow(r int, vis []int) string {
	s := make([]string, 0, len(vis))

	for _, i := range vis {
		var value string
		if i < len(m.rows[r]) {
			value = m.rows[r][i]
		}
		truncated := m.colStyle(i).Render(runewidth.Truncate(value, m.cols[i].Width, "…"))

		var renderedCell string
		if r == m.cursor {
			// Cached Cell-padding + Selected-colors style; see refreshSelStyle.
			renderedCell = m.selCellStyle.Render(truncated)
		} else {
			renderedCell = m.styles.Cell.Render(truncated)
		}
		s = append(s, renderedCell)
	}

	return m.clipToWidth(lipgloss.JoinHorizontal(lipgloss.Top, s...))
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
